DELIMITER //

CREATE DEFINER = CURRENT_USER FUNCTION `isCNPJ`(CNPJ VARCHAR(14))
RETURNS tinyint(4)
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
DECLARE INDICE, SOMA, DIG1, DIG2 INT;
 
/* Calculo do digito 1 */
SET INDICE = 1;
SET SOMA = 0;
 
WHILE (INDICE <= 12) DO
IF (INDICE <= 4) THEN
SET SOMA = SOMA + CAST(SUBSTRING(CNPJ, INDICE, 1) AS UNSIGNED) * (6 - INDICE);
SET INDICE = INDICE + 1;
ELSE
SET SOMA = SOMA + CAST(SUBSTRING(CNPJ, INDICE, 1) AS UNSIGNED) * (14 - INDICE);
SET INDICE = INDICE + 1;
END IF;
END WHILE;
 
SET DIG1 = 11 - (SOMA % 11);
 
IF DIG1 > 9 THEN
SET DIG1 = 0;
END IF;
 
/* Calculo do digito 2 */
SET INDICE = 1;
SET SOMA = 0;
 
WHILE (INDICE <= 13) DO
IF (INDICE <= 5) THEN
SET SOMA = SOMA + CAST(SUBSTRING(CNPJ, INDICE, 1) AS UNSIGNED) * (7 - INDICE);
SET INDICE = INDICE + 1;
ELSE
SET SOMA = SOMA + CAST(SUBSTRING(CNPJ, INDICE, 1) AS UNSIGNED) * (15 - INDICE);
SET INDICE = INDICE + 1;
END IF;
END WHILE;
 
SET DIG2 = 11 - (SOMA % 11);
 
IF DIG2 > 9 THEN
SET DIG2 = 0;
END IF;
 
/* Validando */
IF ((DIG1 = SUBSTRING(CNPJ, LENGTH(CNPJ)-1, 1))
AND (DIG2 = SUBSTRING(CNPJ, LENGTH(CNPJ), 1))) THEN
RETURN TRUE;
ELSE
RETURN FALSE;
END IF;
 
END;//

DELIMITER ;